### ISSUE TITLE
Top menu disappear sometimes

### ISSUE THREAD

**Issue by hikmetmahmut** [abhibagul/Mini-Blogger-Template#1]
Hi, thank you for the great theme.

But the Top menu disappears sometimes. Especially when I clicked a post. can you help me fix this?
and the recent widget is not working

**Comment by abhibagul** [comment]
Go to theme > Edit,
Look for 
```
<script async='async' src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js' type='text/javascript'/>
```

And remove async="async" from it.

**Comment by hikmetmahmut** [comment]
what about the recent post tab? 

and logo - menu - search box are looking separate?

**Comment by abhibagul** [comment]
Share more details, i am unable to understand your issue. 😕

**Comment by hikmetmahmut** [comment]
Firstly, I want to say thank you for your interest.

1 About the Recent Post Tab: its empty nothing is showing. but popular tab and comments tab working fine.
>>> here some screenshots about it https://we.tl/t-2rKGpjqm9L

2 Looking separate problem: I send a screenshot of how to look in mobile
>>> here some screenshots about it https://we.tl/t-pEdvVTFX6r
 
solution offer: maybe you can center each item 
or 
Please make sure that the menu and the search box are on the same row; and that the logo is located right at the center, above these two.

**Comment by abhibagul** [comment]
Try,
Float:none and text-align:center styles for those header items.

And for recent post check if the widget code exist inside it.

**Comment by hikmetmahmut** [comment]
Firstly i want to say thank you for your reply.

Can you reply more spesificly about css changes

and recent tab
`<span class="mino-recent" data-no="5"></span>` in it. but its empty :(

**Comment by abhibagul** [comment]
Share url of the site.
As for the headers you just have to change float to none. And you can make it full width by setting it to 100%
